executor: ${airflow_executor}
config:
  scheduler:
    dag_dir_list_interval: 120
  core:
    dags_folder: "/dags"
    dagbag_import_timeout: 300

defaultAirflowTag: ${airflow_version} 

# Default airflow tag to deploy
defaultAirflowTag: ${airflow_version} 

# Airflow version (Used to make some decisions based on Airflow Version being deployed)
airflowVersion: ${airflow_version} 

env:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: 'wasb-logs' 
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: "azure_default"
  - name: AIRFLOW_CONN_AZURE_DEFAULT
    value: '{"login":"${azure_account_name}"}'

secret:
  - envName: AZURE_CLIENT_ID
    secretName: ${azure_credentials_secret}
    secretKey: AZURE_CLIENT_ID
  - envName: AZURE_CLIENT_SECRET
    secretName: ${azure_credentials_secret}
    secretKey: AZURE_CLIENT_SECRET
  - envName: AZURE_TENANT_ID
    secretName: ${azure_credentials_secret}
    secretKey: AZURE_TENANT_ID


# ${airflow_version}
# ${airflow_frenet_secret}
# ${azure_account_name}
# ${azure_container_name}
# ${dags_sync_prefix}
# ${dag_sync_frequency}
# ${azure_credentials_secret}

webserverSecretKey: ${airflow_frenet_secret}

triggerer:
  extraVolumes:
    - name: synchronised-dags
      emptyDir: {}
  extraVolumeMounts:
    - name: synchronised-dags
      mountPath: /dags
  extraContainers:
    - name: bucket-sync
      envFrom:
        - secretRef:
            name: ${azure_credentials_secret}
      image: valayob/bucket-sync:latest
      imagePullPolicy: Always
      args: [sync-azure-blobs,https://${azure_account_name}.blob.core.windows.net, ${azure_container_name}, ${dags_sync_prefix},/dags,--frequency, '${dag_sync_frequency}']
      volumeMounts:
      - name: synchronised-dags
        mountPath: /dags

workers:
  extraVolumes:
    - name: synchronised-dags
      emptyDir: {}
  extraVolumeMounts:
    - name: synchronised-dags
      mountPath: /dags
  extraInitContainers:
    - name: bucket-sync
      envFrom:
        - secretRef:
            name: ${azure_credentials_secret}
      image: valayob/bucket-sync:latest
      imagePullPolicy: Always
      args: [sync-azure-blobs,https://${azure_account_name}.blob.core.windows.net, ${azure_container_name}, ${dags_sync_prefix},/dags,--only-once]
      volumeMounts:
      - name: synchronised-dags
        mountPath: /dags
# 
scheduler:
  extraVolumes:
    - name: synchronised-dags
      emptyDir: {}
  extraVolumeMounts:
    - name: synchronised-dags
      mountPath: /dags
  extraContainers:
    - name: bucket-sync
      envFrom:
        - secretRef:
            name: ${azure_credentials_secret}
      image: valayob/bucket-sync:latest
      imagePullPolicy: Always
      args: [sync-azure-blobs,https://${azure_account_name}.blob.core.windows.net, ${azure_container_name}, ${dags_sync_prefix},/dags,--frequency,'${dag_sync_frequency}']
      volumeMounts:
      - name: synchronised-dags
        mountPath: /dags