executor: LocalExecutor

defaultAirflowTag: ${airflow_version}

# Default airflow tag to deploy
defaultAirflowTag: ${airflow_version}

# Airflow version (Used to make some decisions based on Airflow Version being deployed)
airflowVersion: ${airflow_version}

env:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: "${airflow_logs_bucket_path}"
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: "google_cloud_default"
  - name: AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
    value: '{"conn_type": "google-cloud-platform", "scope": "https://www.googleapis.com/auth/cloud-platform", "project": "${project_name}", "num_retries": 5}'


webserverSecretKey: ${airflow_frenet_secret}